#!/bin/bash -e

# Var defaults
SESS_NAME=gmod
WINDOW_NAME=0
PANE_NAME=0
USER=srcds
SV_PASSWORD=''
RCON_PASSWORD='PaSsWoRd!'
MAX_PLAYERS=12
MAP=gm_flatgrass
GAMEMODE=sandbox
API_KEY=
COLLECTION=
EXTRA_OPTIONS=''

# Grab vars from command line
while getopts ":M:S:u:s:r:m:o:hg:c:a:dlH:" opt; do
  case $opt in
    S)
      SESS_NAME="$OPTARG"
      ;;
    u)
      USER="$OPTARG"
      ;;
    s)
      SV_PASSWORD="$OPTARG"
      ;;
    r)
      RCON_PASSWORD="$OPTARG"
      ;;
    m)
      MAX_PLAYERS="$OPTARG"
      ;;
    M)
      MAP="$OPTARG"
      ;;
    o)
      EXTRA_OPTIONS="$OPTARG"
      ;;
    g)
      GAMEMODE="$OPTARG"
      ;;
    c)
      COLLECTION="$OPTARG"
      ;;
    a)
      API_KEY="$OPTARG"
      ;;
    d)
      NODOWNLOAD=y
      ;;
    l)
      NOFASTDL=y
      ;;
    H)
      HOSTNAME="$OPTARG"
      ;;
    h)
      cat <<DELIM

    Usage: ./gmod_install.sh

    Option    Description                                  Default
    -----------------------------------------------------------------------
        -u    User to install the server under             srcds
        -s    Set the sv_password option
        -r    Sets the RCON password                       PaSsWoRd!
        -m    Maximum number of players on the server      12
        -g    Game mode                                    sandbox
        -M    Starting map                                 gm_flatgrass
        -S    Session name for tmux                        gmod
        -c    Steam Workshop Collection ID (requires -a)
        -a    API Key
        -d    Skip steamcmd download/validation
        -l    Skip fastdl setup
        -H    Set server name
        -o    Set extra options

DELIM
      exit -1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument" >&2
      exit 1
      ;;
  esac
done

HOMEDIR="/home/$USER"
ARCH=`uname -p`

# Validation: we need to have either both collection and API key, or neither.
if ([ -z "$COLLECTION" ] && [ -n "$API_KEY" ] ) || ( [ -n "$COLLECTION" ] && [ -z "$API_KEY" ] ); then
#if (  ) != (  ); then
  echo "Collection and API key must be provided together."
  exit -1;
fi;

clear

# Opening Banner
cat <<DELIM
     _____        __  __
    / ____|      |  \/  |
   | |  __ ______| \  / | __ _ _ __
   | | |_ |______| |\/| |/ _\` | '_ \\
   | |__| |      | |  | | (_| | | | |
    \_____|      |_|  |_|\__,_|_| |_|

      Garry's Mod Auto-Installer


================================================================================
  Options
================================================================================

   System Architecture: $ARCH
   Username: $USER
   SV Password: $SV_PASSWORD
   RCON Password: $RCON_PASSWORD
   Game Mode: $GAMEMODE
   Starting Map: $MAP
   Player Max: $MAX_PLAYERS
   Tmux Session Name: $SESS_NAME
   Steam Workshop Collection: $COLLECTION
   API Key: $API_KEY
   Extra Options: $EXTRA_OPTIONS
================================================================================


  You have 5 seconds to hit Ctrl-C if the above options don't look right!
DELIM


# Here we go! Update, and add the i386 architecture libraries in.
apt-get update

if [ "$ARCH" = "x86_64" ];
then
  dpkg --add-architecture i386
  apt-get update
  apt-get -y install lib32stdc++6 lib32ncurses5 lib32z1 unzip lighttpd
  if [ -z "$NOFASTDL" ]; then
      apt-get -y install mono-complete
  fi
fi

# Start with the Steam commands
mkdir -p "$HOMEDIR"
useradd $USER || true
wget http://media.steampowered.com/client/steamcmd_linux.tar.gz -O $HOMEDIR/steamcmd_linux.tar.gz
tar xfz $HOMEDIR/steamcmd_linux.tar.gz -C $HOMEDIR
chown -R $USER:$USER $HOMEDIR
chmod 700 $HOMEDIR
chmod +x "$HOMEDIR"/steamcmd.sh

# Execute Steam commands to build the server
if [ -z "$NODOWNLOAD" ]; then
su - -c "$HOMEDIR/steamcmd.sh +login anonymous +force_install_dir $HOMEDIR/gmod +app_update 4020 validate +quit" $USER
su - -c "$HOMEDIR/steamcmd.sh +login anonymous +force_install_dir $HOMEDIR/content/tf2 +app_update 232250 validate +quit" $USER
su - -c "$HOMEDIR/steamcmd.sh +login anonymous +force_install_dir $HOMEDIR/content/css +app_update 232330 validate +quit" $USER
fi

# Build the mount.cfg file
su - -c "(cat <<DELIM
// Auto-generated by G-Man
// https://github.com/b-turchyn/g-man
"mountcfg"
{
        "cstrike"       "$HOMEDIR/content/css/cstrike"
        "tf"            "$HOMEDIR/content/tf2/tf"
}
DELIM
) > $HOMEDIR/gmod/garrysmod/cfg/mount.cfg" $USER

# Build the options string
OPTSTRING=" -game garrysmod +maxplayers $MAX_PLAYERS +map $MAP +gamemode $GAMEMODE +exec server.cfg" 

if [ -n "$SV_PASSWORD" ];
then
  OPTSTRING="$OPTSTRING +sv_password $SV_PASSWORD"
fi

if [ -n "$RCON_PASSWORD" ];
then
  OPTSTRING="$OPTSTRING +rcon_password $RCON_PASSWORD"
fi

if [ -n "$COLLECTION" ] && [ -n "$API_KEY" ];
then
  OPTSTRING="$OPTSTRING +host_workshop_collection $COLLECTION -authkey $API_KEY"
fi

if [ -n "$EXTRA_OPTIONS" ];
then
  OPTSTRING="$OPTSTRING $EXTRA_OPTIONS"
fi

# fastdl
# $HOMEDIR/gmod/garrysmod/cfg/mount.cfg
mkdir -p $HOMEDIR/gmod/SourceRSC
mkdir -p /var/www/html/fastdl
if [ -z "$NOFASTDL" ]; then
unzip SourceRSC.zip -d $HOMEDIR/gmod/SourceRSC
cat <<EOF > $HOMEDIR/gmod/SourceRSC/sourcersc.ini
[GameMod]
GMOD

[GSQryMode]
local

[RedirQryMode]
local

[ServerPath]
/home/srcds/gmod/garrysmod/

[RedirectPath]
/var/www/html/fastdl

[CompressPath]
/tmp/bzd

[RmCPath]
False

[SkipAddons]
False

[SkipMisc]
True

[Debug]
False

[AutoUpdate]
True

[RedirectCleaner]
Off

EOF
fi
if ! grep -i dir-listing /etc/lighttpd/lighttpd.conf; then
    echo "dir-listing.activate = \"enable\"" >> /etc/lighttpd/lighttpd.conf
fi
systemctl restart lighttpd
IP=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1 | head -n1)

su - -c "(cat <<DELIM
hostname $HOSTNAME
sv_allowupload 1
sv_allowdownload 0
sv_downloadurl \"http://$IP/fastdl/\"
DELIM
) > $HOMEDIR/gmod/garrysmod/cfg/server.cfg" $USER

su - -c "(cat <<DELIM
resource.AddWorkshop("1215502383") -- Custom Roles for TTT
resource.AddWorkshop("281454209") -- ttt_Clue_se
resource.AddWorkshop("295897079") -- ttt_lego
resource.AddWorkshop("186012196") -- ttt_cruise
resource.AddWorkshop("504945881") -- Enhanced PlayerModel Selector
resource.AddWorkshop("1817725067") -- [T] Harpoon [TTT]
resource.AddWorkshop("133911194") -- ttt_theship_v1
resource.AddWorkshop("253328815") -- ttt_skyscraper
resource.AddWorkshop("1826848676") -- ttt_community_bowling_v6a
resource.AddWorkshop("147635981") -- ttt_forest_final
resource.AddWorkshop("493066418") -- TTT flashbang
resource.AddWorkshop("1461095720") -- RedMatter Bomb (T Weapon)
resource.AddWorkshop("785294711") -- TTT Taser
resource.AddWorkshop("143190159") -- Prop Hunt
resource.AddWorkshop("590909626") -- TTT Handcuffs
resource.AddWorkshop("254107561") -- TTT Weapon Turret
resource.AddWorkshop("1689087439") -- ttt_mcmansion
resource.AddWorkshop("639521512") -- [TTT] Boomerang
resource.AddWorkshop("2054763555") -- ttt_Devoz
resource.AddWorkshop("1909619554") -- Golden Deagle for Custom Roles for TTT
resource.AddWorkshop("1475589106") -- ttt_bikinibottom
resource.AddWorkshop("1287755005") -- Breath of the Wild - Link [PM, Ragdoll]
resource.AddWorkshop("401568227") -- Crash Twinsanity Player Model
resource.AddWorkshop("348923474") -- Halo: CE Spartan Player Models
resource.AddWorkshop("1319799465") -- Left Shark Accurate Hitbox Playermodel
resource.AddWorkshop("897977074") -- Iron Giant
resource.AddWorkshop("742848707") -- OW || D.Va [PM/RAG/NPC/VOX]
resource.AddWorkshop("562524462") -- OW: Tracer P.M. and Ragdoll
resource.AddWorkshop("944799349") -- Spider-Gwen [PM/NPC/Ragdoll]
resource.AddWorkshop("452065494") -- STAR WARS Darth Vader Playermodel
resource.AddWorkshop("1410172299") -- Strike Freedom Gundam
resource.AddWorkshop("975395650") -- The Witcher 3: Geralt of Rivia Pack [PM/NPC]
resource.AddWorkshop("725320580") -- [The Ship] Donald Trump [Ragdoll/PM]
resource.AddWorkshop("1356525918") -- Kurisu Playermodel/NPC [REUPLOAD]
resource.AddWorkshop("1586172226") -- [P5] Joker P.M.
resource.AddWorkshop("950972267") -- Persona 5 || Futaba [PM]
resource.AddWorkshop("306283778") -- Solaire of Astora Playermodel & NPC
resource.AddWorkshop("188818807") -- Office (ph_office)
resource.AddWorkshop("1083829149") -- Ph_Aperture
resource.AddWorkshop("667484197") -- ph_bank
resource.AddWorkshop("367415423") -- ph_Chalet
resource.AddWorkshop("377716750") -- ph_clue_v2
resource.AddWorkshop("854634173") -- Appearence Miku (Stroll) P.M. & NPC
resource.AddWorkshop("914604640") -- Shimakaze (Kancolle) P.M. & NPC
resource.AddWorkshop("1136706218") -- Yuudachi Kai Ni (Kancolle) Playermodel and NPC
resource.AddWorkshop("870523620") -- Kizuna AI P.M. & NPC
DELIM
) > $HOMEDIR/gmod/garrysmod/lua/autorun/server/resource.lua" $USER

if [ -z "$NOFASTDL" ]; then
# Spin up the tmux session for fastdl
tmux new-session -A -d -s fastdl
tmux send-keys -t "fastdl:$WINDOW_NAME.$PANE_NAME" C-z \
  "cd $HOMEDIR/gmod/SourceRSC/ && sudo mono SourceRSC.exe" Enter
fi

# Spin up the tmux session for gmod
tmux new-session -A -d -s $SESS_NAME

tmux send-keys -t "$SESS_NAME:$WINDOW_NAME.$PANE_NAME" C-z \
  "su - -c '$HOMEDIR/gmod/srcds_run $OPTSTRING' $USER" Enter

cat <<DELIM
     _____        __  __
    / ____|      |  \/  |
   | |  __ ______| \  / | __ _ _ __
   | | |_ |______| |\/| |/ _\` | '_ \\
   | |__| |      | |  | | (_| | | | |
    \_____|      |_|  |_|\__,_|_| |_|

Complete!
https://github.com/b-turchyn/g-man
DELIM
